version: '3'

services:
  webshop_clj:
    image: clojure:latest  # Replace 'your-clojure-image' with your actual image name
    ports:
      - "9001:9001"
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/clojure
      - DB_USER=myuser  # Replace 'myuser' with your desired database username
      - DB_PASSWORD=mypassword  # Replace 'mypassword' with your desired database password
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: clojure
      POSTGRES_USER: myuser  # Replace 'myuser' with your desired database username
      POSTGRES_PASSWORD: mypassword  # Replace 'mypassword' with your desired database password
